function A = A_func(in1,in2)
%A_func
%    A = A_func(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    18-Jan-2024 10:10:31

b = in1(4,:);
phi = in1(1,:);
q = in2(2,:);
r = in2(3,:);
theta = in1(2,:);
t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = tan(theta);
t6 = b+q;
t7 = b+r;
t8 = t5.^2;
t9 = t2+t4;
t10 = 1.0./t3;
t11 = t2.*t6;
t12 = t2.*t7;
t13 = t4.*t6;
t14 = t4.*t7;
t15 = -t14;
t16 = t12+t13;
t17 = t11+t15;
A = reshape([t8.*t17,-t16,t10.*t17,0.0,t5.*t16.*(t8+1.0).*2.0,0.0,t10.^2.*t16.*sin(theta),0.0,0.0,0.0,0.0,0.0,t8.*t9+1.0,t2-t4,t9.*t10,-1.0./3.82e+2],[4,4]);
end
