function B = B_func(in1,in2)
%B_func
%    B = B_func(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    18-Jan-2024 10:10:31

phi = in1(1,:);
theta = in1(2,:);
t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = tan(theta);
t6 = t5.^2;
t7 = 1.0./t3;
B = reshape([1.0,0.0,0.0,0.0,t4.*t6,t2,t4.*t7,0.0,t2.*t6,-t4,t2.*t7,0.0],[4,3]);
end
