function B = B_matrix(in1,in2,g,R_m,R_p,R_g,Omega_e)
%B_matrix
%    B = B_matrix(IN1,IN2,G,R_m,R_p,R_g,Omega_e)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    18-Dec-2023 22:52:59

phi = in1(1,:);
psi = in1(3,:);
theta = in1(2,:);
t2 = cos(phi);
t3 = cos(psi);
t4 = cos(theta);
t5 = sin(phi);
t6 = sin(psi);
t7 = sin(theta);
t8 = tan(theta);
t9 = 1.0./t4;
B = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t5.*t8,t2,t5.*t9,0.0,0.0,0.0,0.0,0.0,0.0,t2.*t8,-t5,t2.*t9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t3.*t4,t4.*t6,-t7,0.0,0.0,0.0,0.0,0.0,0.0,-t2.*t6+t3.*t5.*t7,t2.*t3+t5.*t6.*t7,t4.*t5,0.0,0.0,0.0,0.0,0.0,0.0,t5.*t6+t2.*t3.*t7,-t3.*t5+t2.*t6.*t7,t2.*t4,0.0,0.0,0.0],[9,6]);
end
